Repository argentlabs/argent-x, pull requests merged in 2023-03, with the labels that each got.

#1787 [BLO-820] Users can fill in a multisig creation form [API logic]
  packages/extension/src/background/accountMessaging.ts
  packages/extension/src/background/wallet.ts
  packages/extension/src/shared/messages/AccountMessage.ts
  packages/extension/src/shared/wallet.model.ts
  packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/CreateMultisigStartScreen.tsx
  packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigFirstStep.tsx
  packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigSecondStep.tsx
  packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigThirdStep.tsx
  packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/ScreenLayout.tsx
  packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/useCreateMultisig.ts
  packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/useCreateMultisigForm.ts
  packages/extension/src/ui/features/accounts/multisig/NewMultisigScreen.tsx
  packages/extension/src/ui/services/backgroundAccounts.ts
  packages/extension/src/ui/useEntryRoute.tsx
  packages/ui/src/components/RoundButton.tsx
  packages/ui/src/components/index.ts
Labels: multisig

#1821 Blo 832
  packages/extension/src/background/accountMessaging.ts
  packages/extension/src/background/index.ts
  packages/extension/src/background/transactions/transactionMessaging.ts
  packages/extension/src/background/wallet.ts
  packages/extension/src/shared/api/constants.ts
  packages/extension/src/shared/messages/AccountMessage.ts
  packages/extension/src/shared/multisig/store.ts
  packages/extension/src/shared/wallet.model.ts
  packages/extension/src/ui/AppRoutes.tsx
  packages/extension/src/ui/features/accounts/Account.ts
  packages/extension/src/ui/features/accounts/AccountListItem.tsx
  packages/extension/src/ui/features/accounts/AccountListScreen.tsx
  packages/extension/src/ui/features/accounts/AccountListScreenItem.tsx
  packages/extension/src/ui/features/accounts/AddNewAccountScreen.tsx
  packages/extension/src/ui/features/accounts/GroupedAccountList.tsx
  packages/extension/src/ui/features/accounts/accounts.service.ts
  packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/useCreateMultisig.ts
  packages/extension/src/ui/features/accounts/multisig/types.ts
  packages/extension/src/ui/features/accounts/multisig/useSignerKey.tsx
  packages/extension/src/ui/features/accounts/upgrade.service.ts
  packages/extension/src/ui/features/accounts/useAddAccount.ts
  packages/extension/src/ui/features/accounts/usePublicKey.ts
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/CreateMultisigStartScreen.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/MultisigFirstStep.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/MultisigSecondStep.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/MultisigThirdStep.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/ScreenLayout.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/useCreateMultisig.ts
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/useCreateMultisigForm.ts
  packages/extension/src/ui/features/multisig/JoinMultisigScreen.tsx
  packages/extension/src/ui/features/multisig/Multisig.ts
  packages/extension/src/ui/features/multisig/MultisigDeleteModal.tsx
  packages/extension/src/ui/features/multisig/MultisigListScreenItem.tsx
  packages/extension/src/ui/features/multisig/NewMultisigScreen.tsx
  packages/extension/src/ui/features/multisig/hooks/useMultisigDataForSigner.ts
  packages/extension/src/ui/features/multisig/hooks/useMultisigInfo.ts
  packages/extension/src/ui/features/multisig/hooks/useMultisigStatus.ts
  packages/extension/src/ui/features/multisig/multisig.model.ts
  packages/extension/src/ui/features/multisig/multisig.service.ts
  packages/extension/src/ui/features/multisig/multisig.state.ts
  packages/extension/src/ui/services/backgroundAccounts.ts
  packages/extension/test/wallet.test.ts
Labels: multisig

#1880 BLO-874 chore: remove no longer needed implementation check
  packages/extension/src/shared/account/details/getEscape.ts
  packages/extension/src/shared/account/details/getGuardian.ts
  packages/extension/src/shared/account/details/getImplementation.ts
Labels: 2fa

#1869 BLO-864 chore: 2fa headers
  packages/extension/src/shared/shield/jwtFetcher.ts
Labels: 2fa

#1875 [BLO-863] Test setup for multisig
  .github/workflows/test-e2e.yml
  .github/workflows/test.yml
  packages/extension/src/ui/features/accounts/accountMetadata.test.ts
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/MultisigFirstStep.test.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/MultisigFirstStep.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/MultisigSecondStep.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/ScreenLayout.tsx
  packages/extension/test/account.mock.ts
Labels: multisig

#1868 BLO-859 fix: 2fa checks
  packages/extension/src/background/shieldMessaging.ts
  packages/extension/src/shared/messages/ShieldMessage.ts
  packages/extension/src/shared/shield/GuardianSignerArgentX.ts
  packages/extension/src/shared/shield/backend/account.ts
  packages/extension/src/shared/shield/register.ts
  packages/extension/src/shared/shield/verifiedEmail.ts
  packages/extension/src/ui/features/actions/ActionScreen.tsx
  packages/extension/src/ui/features/shield/ShieldAccountStartScreen.tsx
  packages/extension/src/ui/features/shield/WithArgentShieldVerified.tsx
  packages/extension/src/ui/features/shield/escape/EscapeWarningScreen.tsx
  packages/extension/src/ui/features/shield/usePendingChangingGuardian.ts
Labels: 2fa

#1842 BLO-838 chore: use endpoint to determine token expiry
  packages/extension/src/shared/shield/GuardianSignerArgentX.ts
  packages/guardian/src/services/GuardianSigner.ts
Labels: 2fa

#1877 Feat/multisig signers account
  packages/extension/src/background/transactions/transactionExecution.ts
  packages/extension/src/background/wallet.ts
  packages/extension/src/shared/multisig/account.test.ts
  packages/extension/src/shared/multisig/account.ts
  packages/extension/src/shared/multisig/mocks/executeTransaction.mock.ts
  packages/extension/src/shared/multisig/multisig.model.ts
  packages/extension/src/shared/multisig/multisig.service.ts
  packages/extension/src/shared/multisig/signer.ts
  packages/extension/src/shared/utils/starknetNetwork.ts
  packages/extension/src/ui/features/multisig/hooks/useMultisigDataForSigner.ts
  packages/extension/src/ui/features/multisig/multisig.model.ts
Labels: multisig

#1887 BLO-877 chore: reduce expiry time
  packages/extension/src/shared/shield/jwt.ts
Labels: 2fa

#1902 BLO-875 feat: 2fa analytics
  packages/extension/src/shared/analytics.ts
  packages/extension/src/shared/shield/validation.test.ts
  packages/extension/src/shared/shield/validation.ts
  packages/extension/src/ui/features/onboarding/OnboardingDisclaimerScreen.tsx
  packages/extension/src/ui/features/onboarding/OnboardingFinishScreen.tsx
  packages/extension/src/ui/features/onboarding/OnboardingPasswordScreen.tsx
  packages/extension/src/ui/features/onboarding/OnboardingRestoreSeed.tsx
  packages/extension/src/ui/features/onboarding/OnboardingStartScreen.tsx
  packages/extension/src/ui/features/shield/ShieldAccountActionScreen.tsx
  packages/extension/src/ui/features/shield/ShieldAccountEmailScreen.tsx
  packages/extension/src/ui/features/shield/ShieldAccountOTPScreen.tsx
  packages/extension/src/ui/features/shield/ShieldAccountStartScreen.tsx
  packages/extension/src/ui/features/shield/ShieldBaseFinishScreen.tsx
  packages/extension/src/ui/features/shield/ShieldValidationErrorScreen.tsx
  packages/extension/src/ui/features/shield/escape/EscapeGuardian.tsx
  packages/extension/src/ui/features/shield/escape/EscapeSigner.tsx
  packages/extension/src/ui/features/shield/escape/EscapeWarningScreen.tsx
  packages/extension/src/ui/features/shield/useAccountGuardian.ts
  packages/extension/src/ui/features/shield/useShieldTracking.ts
  packages/extension/src/ui/features/shield/useShieldVerifiedEmail.ts
  packages/extension/src/ui/services/analytics.ts
Labels: 2fa

#1907 chore: ci flags for 2fa
  .github/workflows/release.yml
Labels: 2fa

#1910 BLO-858 chore: verified dapp ui
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/index.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/VerifiedDappBanner/VerifiedDappModal.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/VerifiedDappBanner/index.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/index.tsx
Labels: RC

#1916 chore: enable verified dapps
  .github/workflows/release.yml
Labels: RC

#1917 Hotfix/nft details screen
  packages/extension/src/ui/features/accountNfts/NftScreen.tsx
  packages/extension/src/ui/features/accountNfts/SendNftScreen.tsx
  packages/extension/src/ui/features/accountNfts/aspect.model.ts
  packages/extension/src/ui/features/accountNfts/aspect.service.ts
Labels: RC

#1924 BLO-912 fix: always reset
  packages/extension/src/ui/features/shield/ShieldAccountOTPScreen.tsx
  packages/extension/src/ui/features/shield/ShieldBaseEmailScreen.tsx
Labels: RC

#1928 BLO-960 feat: 2fa links
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/VerifiedDappBanner/VerifiedDappModal.tsx
  packages/extension/src/ui/features/shield/escape/EscapeGuardian.tsx
  packages/extension/src/ui/features/shield/escape/EscapeSigner.tsx
  packages/extension/src/ui/features/shield/ui/ShieldExternalLinkButton.tsx
  packages/extension/src/ui/features/shield/ui/ShieldLearnMoreButton.tsx
Labels: 2fa, RC

#1929 BLO-904 feat: check if account can have 2fa enabled
  packages/extension/src/shared/account/details/getImplementation.ts
  packages/extension/src/ui/features/accountEdit/AccountEditScreen.tsx
Labels: 2fa, RC

#1933 fix: bundlesize, run test on main pr's
  .github/workflows/test-e2e.yml
  .github/workflows/test.yml
  packages/extension/package.json
Labels: RC

#1936 BLO-922 fix: 2fa check
  packages/extension/src/shared/account/details/getImplementation.ts
  packages/extension/src/ui/features/accountEdit/AccountEditScreen.tsx
  packages/extension/src/ui/features/shield/ShieldAccountNotDeployed.tsx
  packages/extension/src/ui/features/shield/ShieldAccountStartScreen.tsx
Labels: 2fa, RC

#1832 [BLO-792] Users can review multisig settings before it has been deployed
  packages/extension/e2e/Dockerfile
  packages/extension/src/shared/api/fetcher.ts
  packages/extension/src/shared/multisig/multisig.service.ts
  packages/extension/src/shared/shield/backend/account.ts
  packages/extension/src/shared/shield/jwtFetcher.ts
  packages/extension/src/shared/transactionReview.service.ts
  packages/extension/src/shared/transactionSimulation/types.ts
  packages/extension/src/ui/AppRoutes.tsx
  packages/extension/src/ui/features/accountEdit/AccountEditButtons.tsx
  packages/extension/src/ui/features/accountEdit/AccountEditButtonsMultisig.tsx
  packages/extension/src/ui/features/accountEdit/AccountEditScreen.tsx
  packages/extension/src/ui/features/accounts/usePublicKey.ts
  packages/extension/src/ui/features/actions/transaction/useTransactionReview.ts
  packages/extension/src/ui/features/actions/transaction/useTransactionSimulation.ts
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/CreateMultisigStartScreen.tsx
  packages/extension/src/ui/features/multisig/MultisigConfirmationsScreen.tsx
  packages/extension/src/ui/features/multisig/MultisigOwnersScreen.tsx
  packages/extension/src/ui/features/multisig/MultisigSettingsWrapper.tsx
  packages/extension/src/ui/features/multisig/hooks/useMultisigData.ts
  packages/extension/src/ui/features/multisig/hooks/useMultisigInfo.ts
  packages/extension/src/ui/features/multisig/multisig.state.ts
  packages/extension/src/ui/routes.ts
  packages/extension/src/ui/services/addresses.ts
  packages/extension/src/ui/services/argentApiFetcher.ts
Labels: multisig

#1903 [BLO-889] Add UI screens for deployed multisig accounts
  packages/extension/src/ui/AppRoutes.tsx
  packages/extension/src/ui/features/accountEdit/AccountEditButtonsMultisig.tsx
  packages/extension/src/ui/features/multisig/AddOwnerForm.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/CreateMultisigStartScreen.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/MultisigFirstStep.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/MultisigSecondStep.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/ScreenLayout.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/useCreateMultisigForm.ts
  packages/extension/src/ui/features/multisig/MultisigAddOwnersScreen.tsx
  packages/extension/src/ui/features/multisig/MultisigConfirmationsScreen.tsx
  packages/extension/src/ui/features/multisig/MultisigOwnersScreen.tsx
  packages/extension/src/ui/features/multisig/MultisigSettingsWrapper.tsx
  packages/extension/src/ui/features/multisig/SetConfirmationsInput.tsx
  packages/extension/src/ui/features/multisig/hooks/useCreateMultisig.ts
  packages/extension/src/ui/features/multisig/hooks/useCreateMultisigForm.ts
  packages/extension/src/ui/routes.ts
Labels: multisig

#1962 fix: pin devnet
  packages/extension/e2e/Dockerfile
Labels: RC

#1909 [BLO-890] Transaction confirmation screen multisig
  packages/extension/src/background/transactions/transactionExecution.ts
  packages/extension/src/background/transactions/transactionMessaging.ts
  packages/extension/src/shared/messages/TransactionMessage.ts
  packages/extension/src/shared/multisig/multisig.service.ts
  packages/extension/src/shared/transactions.ts
  packages/extension/src/shared/wallet.model.ts
  packages/extension/src/ui/features/actions/ActionScreen.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionIcon/AddOwnerIcon.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionIcon/UpdateThresholdIcon.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionIcon/index.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionTitle.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/index.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/MultisigBanner.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/TransactionActions.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/index.tsx
  packages/extension/src/ui/features/actions/transaction/types.ts
  packages/extension/src/ui/features/actions/utils.ts
  packages/extension/src/ui/features/multisig/AddOwnerForm.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/MultisigFirstStep.tsx
  packages/extension/src/ui/features/multisig/CreateMultisigScreen/MultisigSecondStep.tsx
  packages/extension/src/ui/features/multisig/MultisigAddOwnersScreen.tsx
  packages/extension/src/ui/features/multisig/MultisigConfirmationsScreen.tsx
  packages/extension/src/ui/features/multisig/MultisigOwnersScreen.tsx
  packages/extension/src/ui/features/multisig/SetConfirmationsInput.tsx
  packages/extension/src/ui/features/multisig/hooks/useCreateMultisigForm.ts
  packages/extension/src/ui/features/multisig/hooks/useUpdateThreshold.ts
  packages/ui/src/components/Progress.tsx
  packages/ui/src/components/SplitProgress.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/theme/index.tsx
Labels: multisig

#1961 BLO-892 hotfix: ensure sparse account object
  packages/extension/src/ui/services/backgroundAccounts.ts
Labels: RC

#1932 [BLO-700] Transaction transformers for Multisig
  packages/extension/src/background/transactions/transactionExecution.ts
  packages/extension/src/background/transactions/transactionMessaging.ts
  packages/extension/src/shared/call/addMultisigSignersCall.ts
  packages/extension/src/shared/call/setMultisigThresholdCalls.ts
  packages/extension/src/shared/messages/TransactionMessage.ts
  packages/extension/src/shared/multisig/account.ts
  packages/extension/src/shared/multisig/multisig.model.ts
  packages/extension/src/shared/multisig/multisig.service.ts
  packages/extension/src/shared/multisig/pendingTransactionsStore.ts
  packages/extension/src/shared/transactions.ts
  packages/extension/src/shared/utils/starknetNetwork.ts
  packages/extension/src/ui/features/accountActivity/AccountActivityContainer.tsx
  packages/extension/src/ui/features/accountActivity/PendingMultisigTransactions.tsx
  packages/extension/src/ui/features/accountActivity/TransactionListItem.tsx
  packages/extension/src/ui/features/accountActivity/transform/transaction/transformTransaction.ts
  packages/extension/src/ui/features/accountActivity/transform/transaction/transformers/addMultisigTransformer.ts
  packages/extension/src/ui/features/accountActivity/transform/transaction/transformers/changeMultisigThresholdTransformer.ts
  packages/extension/src/ui/features/accountActivity/transform/transaction/transformers/pendingMultisigTransactionAdapter.ts
  packages/extension/src/ui/features/accountActivity/transform/type.ts
  packages/extension/src/ui/features/accountActivity/ui/TransactionIcon.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/index.tsx
  packages/extension/src/ui/features/multisig/MultisigConfirmationsScreen.tsx
  packages/extension/src/ui/features/multisig/SetConfirmationsInput.tsx
  packages/extension/src/ui/features/multisig/multisigTransactions.state.ts
Labels: multisig

#1980 Feat: Blo 697 user can recover their multisig account
  packages/extension/src/background/wallet.ts
  packages/extension/src/ui/features/accounts/AddNewAccountScreen.tsx
Labels: multisig

#1956 [BLO-696] User can see Multisig tx details screen
  .github/workflows/test-e2e.yml
  packages/extension/src/ui/AppRoutes.tsx
  packages/extension/src/ui/features/accountActivity/PendingMultisigTransactions.tsx
  packages/extension/src/ui/features/actions/ActionScreen.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionIcon/index.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/MultisigBanner.tsx
  packages/extension/src/ui/features/actions/utils.ts
  packages/extension/src/ui/features/multisig/MultisigPendingTransactionDetailsScreen.tsx
  packages/extension/src/ui/features/multisig/TransactionConfirmationsScreen.tsx
  packages/extension/src/ui/features/multisig/hooks/useMultisigPendingTransaction.ts
  packages/extension/src/ui/features/multisig/hooks/useMultisigRequest.ts
  packages/extension/src/ui/routes.ts
Labels: multisig

#1963 [BLO-905] Remove signer from multisig
  packages/extension/src/background/transactions/transactionMessaging.ts
  packages/extension/src/shared/call/changeMultisigSignersCall.ts
  packages/extension/src/shared/messages/TransactionMessage.ts
  packages/extension/src/shared/multisig/account.test.ts
  packages/extension/src/shared/multisig/multisig.model.ts
  packages/extension/src/shared/multisig/multisig.service.ts
  packages/extension/src/shared/transactions.ts
  packages/extension/src/shared/wallet.model.ts
  packages/extension/src/ui/AppRoutes.tsx
  packages/extension/src/ui/features/accountActivity/transform/transaction/transformTransaction.ts
  packages/extension/src/ui/features/accountActivity/transform/transaction/transformers/addMultisigTransformer.ts
  packages/extension/src/ui/features/accountActivity/transform/transaction/transformers/changeMultisigTransformer.ts
  packages/extension/src/ui/features/accountActivity/transform/type.ts
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionIcon/RemoveOwnerIcon.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionIcon/index.tsx
  packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionTitle.tsx
  packages/extension/src/ui/features/actions/transaction/types.ts
  packages/extension/src/ui/features/actions/utils.ts
  packages/extension/src/ui/features/multisig/MultisigConfirmationsScreen.tsx
  packages/extension/src/ui/features/multisig/MultisigOwnersScreen.tsx
  packages/extension/src/ui/features/multisig/MultisigRemoveOwnerScreen.tsx
  packages/extension/src/ui/routes.ts
Labels: multisig
